ARG UBUNTU_VERSION=18.04
ARG CUDA_VERSION=11.1.1
ARG CUDNN_VERSION=8

FROM nvidia/cuda:${CUDA_VERSION}-cudnn${CUDNN_VERSION}-devel-ubuntu${UBUNTU_VERSION}

ARG UID=1000
ARG USER_NAME=nlplab7
ARG CONDA_ENV_NAME=QSG-Transformer
ARG PYTHON_VERSION=3.8
ARG DIR_NAME=QSG-Transformer

# Let us install tzdata painlessly
ENV DEBIAN_FRONTEND=noninteractive

# Needed for string substitution
SHELL ["/bin/bash", "-c"]
RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    ccache \
    cmake \
    curl \
    git \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libzmq3-dev \
    libjpeg-dev \
    libpng-dev \
    libsm6 \
    libxext6 \
    libxrender-dev \
    pkg-config \
    software-properties-common \
    ssh \
    sudo \
    unzip \
    vim \
    wget
RUN apt-get install default-jdk -y
RUN rm -rf /var/lib/apt/lists/*

ENV LANG C.UTF-8
RUN curl -o /tmp/miniconda.sh -sSL http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod +x /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -bfp /usr/local && \
    rm /tmp/miniconda.sh
RUN conda update -y conda

# Create a user
RUN adduser $USER_NAME -u $UID --quiet --gecos "" --disabled-password && \
    echo "$USER_NAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USER_NAME && \
    chmod 0440 /etc/sudoers.d/$USER_NAME
RUN sudo usermod -a -G sudo $USER_NAME

USER $USER_NAME
ENV TERM xterm-256color
SHELL ["/bin/bash", "-c"]

COPY . /$DIR_NAME
WORKDIR /$DIR_NAME

RUN conda create -n $CONDA_ENV_NAME python=$PYTHON_VERSION
RUN echo "source activate ${CONDA_ENV_NAME}" >> ~/.bashrc

RUN source activate ${CONDA_ENV_NAME} && \
    pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html && \
    pip install -r requirements.txt